language: ruby
rvm:
  - 2.2

services:
    - docker

install:
  - docker build -t pipelinetest .
  - docker run -d -p 127.0.0.1:80:80 --name pipelinetest pipelinetest

script:
    - docker ps | grep -q pipelinetest


