language: ruby
rvm:
  - 2.2

services:
    - docker

install:
  - docker build -t pipelinetest .
  - docker run -d -p 127.0.0.1:80:80 --name pipelinetest pipelinetest
  - gem install serverspec --no-ri --no-rdoc

script:
    - docker ps | grep -q pipelinetest
    - rake spec

notifications:
  email:
    recipients:
      - v.adamec@seznam.cz
    on_success: always
    on_failure: always

